### ISSUE TITLE
Отображение актуальной версии build_all падает

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#35]
vood@vood-ThinkPad:~/ws/maxscale-jenkins-jobs$ git log
commit 89af41b82fa9b678bc305bb332df5bdd7b1359f9
Author: Alexander Kaluzhniy <GALIAF1995@GMAIL.COM>
Date:   Fri Mar 17 21:32:04 2017 +0300

    #8043 added subjobs autokiller to build_all & run_test_matrix (#150)

vood@vood-ThinkPad:~/ws/maxscale-jenkins-jobs$ ../yaml-unfolding/main.py --files maxscale_jobs/build_all.yaml --call-graph --yaml-root maxscale_jobs/ --call-display text
Traceback (most recent call last):
  File "../yaml-unfolding/main.py", line 47, in <module>
    yaml_unfolder.call_graph.unfold_file(file_name)
  File "/home/vood/ws/yaml-unfolding/job_visualization/call_graph.py", line 82, in unfold_file
    q.extend(self.get_calls(yaml_config, name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 120, in get_calls_from_dict
    calls.extend(self.get_calls_from_dict(value, from_name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 117, in get_calls_from_dict
    calls.extend(self.get_calls_from_dict(file_dict[key], from_name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 117, in get_calls_from_dict
    calls.extend(self.get_calls_from_dict(file_dict[key], from_name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 120, in get_calls_from_dict
    calls.extend(self.get_calls_from_dict(value, from_name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 115, in get_calls_from_dict
    calls.append(self.extract_call(file_dict['trigger-parameterized-builds'], from_name))
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 131, in extract_call
    file_data = self.get_data_from_name(project)
  File "/home/vood/ws/yaml-unfolding/job_visualization/yaml_unfolder.py", line 100, in get_data_from_name
    return self.file_index.get_by_name(name)
  File "/home/vood/ws/yaml-unfolding/job_visualization/file_index.py", line 43, in get_by_name
    return self.files[name]
TypeError: unhashable type: 'list'

**Comment by missingdays** [comment]
В файле `https://github.com/mariadb-corporation/maxscale-jenkins-jobs/blob/master/maxscale_jobs/include/parametrized_triggerred_subjobs_killer/publisher-trigger-parametrized-builds.yaml` имя проекта, которого вызывают, указано как список имен, состоящий из одного имени, поэтому эта ошибка и появляется. Если требуется, я добавлю обработку такого случая. Но тогда возникает вопрос - может ли это быть вызов нескольких job в одном файле? То есть может ли этот список состоять из более чем одного имени?

**Comment by missingdays** [comment]
Отправил пулл реквест #41 

Добавил возможность вызывать несколько job одним файлом.

### Steps to reproduce

1. Из папки `maxscale-jenkins-jobs` с актуальной версией выполнить команду
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --yaml-root maxscale_jobs/ --call-graph 
```
Убедиться, что файл `build_all.yaml_call.svg` сгенерирован успешно.
