### ISSUE TITLE
Циклические зависимости в call graph

### ISSUE THREAD

**Issue by missingdays** [OSLL/jenkins_job_builder_visualization#59]
Анализ на циклические зависимости в call графах.

**Comment by missingdays** [comment]
Отправил pull request #63 

Добавил анализ на циклические зависимости в call graph.

### Steps to reproduce

1. Из папки `maxscale-jenkins-jobs` запустить
```
../jenkins_job_builder_visualization/main.py --analysis cyclic_deps
```
Убедиться, что тест на Call graph выдал OK

2. Добавить циклическую зависимость, например, в `remove_lock.yaml` добавить
```yaml
publishers:
    trigger-builds:
        - project: 'build_regular'
```

Запустить
```
../jenkins_job_builder_visualization/main.py --analysis cyclic_deps
```

Убедиться, что обнаружился цикл
```
Cyclic dependencies in call graph test
Found cycle build -> cleanup -> smart_remove_lock -> remove_lock -> build_regular -> build
```

**Comment by zmm** [comment]
На первой команде падает 

vood@vood-ThinkPad:~/ws/maxscale-jenkins-jobs$ ../jenkins_job_builder_visualization/main.py --analysis cyclic_deps

Traceback (most recent call last):
  File "../jenkins_job_builder_visualization/main.py", line 49, in <module>
    yaml_unfolder = YamlUnfolder(root=yaml_root, rank_dir=args.rank_dir)
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/yaml_unfolder.py", line 48, in __init__
    self.init_file_index()
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/yaml_unfolder.py", line 65, in init_file_index
    self.file_index.files = self.file_index.load_files(self.root)
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/file_index.py", line 25, in load_files
    for filename in os.listdir(path):
OSError: [Errno 2] No such file or directory: ''
